/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-2",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_J2NHHmzCI",
  "aws_user_pools_web_client_id": "7p37jt66hrd0ipceonigoju1ne",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "Auth": {
      "Cognito": {
          "region": "us-east-2",
          "userPoolId": "us-east-2_U0diJv929",
          "userPoolWebClientId": "69g0o5hvmc78i0olmmktooho42",
          "mandatorySignIn": false,
          "authenticationFlowType": "USER_SRP_AUTH",
          "loginWith": {
              "oauth": {
                  "domain": "",
                  "scopes": [],
                  "redirectSignIn": "",
                  "redirectSignOut": "",
                  "responseType": "code"
              },
              "username": "false",
              "email": "true",
              "phone": "false"
          }
      }
  }
};


export default awsmobile;
